variables:
  PROJECT_NAME: poc
  DOMAIN_NAME: datalake_test
  STAGE_NAME: $CI_COMMIT_REF_SLUG
  PYTHON_CODE_PATH: "./"
  PYENV_VERSION: 3.13
  TARGET_REPO_NAME: "aws-data-platform-framework"


include:
  - project: 'erwan.simon/devops-platform-ci-templates'
    ref: 'v2.1.0'
    file:
      - 'base.yml'
      - 'docker.yml'
      - 'python.yml'
      - 'mirror_to_github.yml'

stages:
  - init
  - format
  - security
  - unit_tests
  - deploy_integration_tests
  - run_integration_tests
  - mirror_to_github

#############################################################
######################## INTEGRATION-TESTS ##################
#############################################################

deploy_integration_tests:
  stage: deploy_integration_tests
  allow_failure: false
  script:
    - mkdir -p ~/.aws
    - echo "${CI_JOB_JWT_V2}" > /tmp/web_identity_token
    - echo -e "[profile default]\nrole_arn=${GITLAB_ROLE_ARN}\nweb_identity_token_file=/tmp/web_identity_token" > ~/.aws/config
    - cd test
    - terraform init -backend-config="bucket=$TERRAFORM_BACKEND_BUCKET" -backend-config="dynamodb_table=$TERRAFORM_BACKEND_DYNAMODB"
    - terraform workspace new $CI_COMMIT_BRANCH || terraform workspace select $CI_COMMIT_BRANCH
    - terraform apply --auto-approve
  needs:
    - init_ecr_token
  except:
    refs:
      - tags

run_integration_tests:
  stage: run_integration_tests
  allow_failure: false
  script:
    - export step_function_arn="arn:aws:states:${AWS_DEFAULT_REGION}:${ACCOUNT_ID}:stateMachine:${PROJECT_NAME}_datalake_test_${STAGE_NAME}_tests"
    - pip install boto3
    - python test/utils/run_integration_tests.py ${step_function_arn}
  needs:
    - init_ecr_token
    - deploy_integration_tests
  variables:
    PYTHONUNBUFFERED: "1"
  except:
    refs:
      - tags
